Repository puppetlabs/puppetlabs-translate, pull requests merged in 2019-12, with the labels that each got.

#61 pdksync - FM-8499 remove ubuntu 14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#63 pdksync - "MODULES-10242 Add ubuntu14 support back to the modules"
  metadata.json
  provision.yaml
Labels: feature

#64 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#65 pdksync - (maint) travis updates: bundler and slack
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#67 pdksync - FM-8834 - Add GitHub action workflow
  .github/workflows/release.yml
Labels: maintenance
